// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReqLens.Infrastructure.Persistence;

#nullable disable

namespace ReqLens.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907171417_AddIssueResolution")]
    partial class AddIssueResolution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReqLens.Domain.Ambiguity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequirementId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ResolvedSelections")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("ambiguities", (string)null);
                });

            modelBuilder.Entity("ReqLens.Domain.AmbiguityQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmbiguityId")
                        .HasColumnType("uuid");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AmbiguityId");

                    b.ToTable("ambiguity_questions", (string)null);
                });

            modelBuilder.Entity("ReqLens.Domain.Contradiction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChosenRequirementId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("RequirementIdA")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequirementIdB")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ResolutionQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("contradictions", (string)null);
                });

            modelBuilder.Entity("ReqLens.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("RawContent")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("ReqLens.Domain.QualityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActorScore")
                        .HasColumnType("integer");

                    b.Property<int>("Clarity")
                        .HasColumnType("integer");

                    b.Property<int>("Completeness")
                        .HasColumnType("integer");

                    b.Property<int>("Consistency")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("HasActorCount")
                        .HasColumnType("integer");

                    b.Property<int>("HasMeasurableConstraintCount")
                        .HasColumnType("integer");

                    b.Property<int>("InvolvedInContradictionCount")
                        .HasColumnType("integer");

                    b.Property<int>("LlmClarity")
                        .HasColumnType("integer");

                    b.Property<int>("LlmSpecificity")
                        .HasColumnType("integer");

                    b.Property<int>("MeasurableConstraintCoverage")
                        .HasColumnType("integer");

                    b.Property<int>("Overall")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionScore")
                        .HasColumnType("integer");

                    b.Property<int>("RequirementCount")
                        .HasColumnType("integer");

                    b.Property<int>("Specificity")
                        .HasColumnType("integer");

                    b.Property<int>("Testability")
                        .HasColumnType("integer");

                    b.Property<int>("UnansweredQuestionCount")
                        .HasColumnType("integer");

                    b.Property<int>("UnresolvedContradictionCount")
                        .HasColumnType("integer");

                    b.Property<int>("VagueCount")
                        .HasColumnType("integer");

                    b.Property<int>("VagueScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("quality_scores", (string)null);
                });

            modelBuilder.Entity("ReqLens.Domain.Requirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequirementId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SourceLine")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "RequirementId")
                        .IsUnique();

                    b.ToTable("requirements", (string)null);
                });

            modelBuilder.Entity("ReqLens.Domain.Ambiguity", b =>
                {
                    b.HasOne("ReqLens.Domain.Document", "Document")
                        .WithMany("Ambiguities")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ReqLens.Domain.AmbiguityQuestion", b =>
                {
                    b.HasOne("ReqLens.Domain.Ambiguity", "Ambiguity")
                        .WithMany("Questions")
                        .HasForeignKey("AmbiguityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ambiguity");
                });

            modelBuilder.Entity("ReqLens.Domain.Contradiction", b =>
                {
                    b.HasOne("ReqLens.Domain.Document", "Document")
                        .WithMany("Contradictions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ReqLens.Domain.QualityScore", b =>
                {
                    b.HasOne("ReqLens.Domain.Document", "Document")
                        .WithOne("QualityScore")
                        .HasForeignKey("ReqLens.Domain.QualityScore", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ReqLens.Domain.Requirement", b =>
                {
                    b.HasOne("ReqLens.Domain.Document", "Document")
                        .WithMany("Requirements")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ReqLens.Domain.Ambiguity", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ReqLens.Domain.Document", b =>
                {
                    b.Navigation("Ambiguities");

                    b.Navigation("Contradictions");

                    b.Navigation("QualityScore");

                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
